// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file proto/oneofenum/oneof_enum.proto (package proto.oneofenum, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/oneofenum/oneof_enum.proto.
 */
export const file_proto_oneofenum_oneof_enum: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CiBwcm90by9vbmVvZmVudW0vb25lb2ZfZW51bS5wcm90bxIPcHJvdG8ub25lb2ZlbnVtIk8KEE9uZW9mRW51bU1lc3NhZ2USNAoMZXhhbXBsZV9lbnVtGAEgASgOMhwucHJvdG8ub25lb2ZlbnVtLkV4YW1wbGVFbnVtSABCBQoDb25lKkMKC0V4YW1wbGVFbnVtEhwKGEVYQU1QTEVfRU5VTV9VTlNQRUNJRklFRBAAEhYKEkVYQU1QTEVfRU5VTV9GSVJTVBABQs8BChNjb20ucHJvdG8ub25lb2ZlbnVtQg5PbmVvZkVudW1Qcm90b1ABWktnaXRodWIuY29tL2dycGMtZWNvc3lzdGVtL2dycGMtZ2F0ZXdheS92Mi9leGFtcGxlcy9pbnRlcm5hbC9wcm90by9vbmVvZmVudW2iAgNQT1iqAg9Qcm90by5PbmVvZmVudW3KAg9Qcm90b1xPbmVvZmVudW3iAhtQcm90b1xPbmVvZmVudW1cR1BCTWV0YWRhdGHqAhBQcm90bzo6T25lb2ZlbnVtYgZwcm90bzM",
  );

/**
 * @generated from message proto.oneofenum.OneofEnumMessage
 */
export type OneofEnumMessage = Message<"proto.oneofenum.OneofEnumMessage"> & {
  /**
   * @generated from oneof proto.oneofenum.OneofEnumMessage.one
   */
  one:
    | {
        /**
         * @generated from field: proto.oneofenum.ExampleEnum example_enum = 1;
         */
        value: ExampleEnum;
        case: "exampleEnum";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message proto.oneofenum.OneofEnumMessage.
 * Use `create(OneofEnumMessageSchema)` to create a new message.
 */
export const OneofEnumMessageSchema: GenMessage<OneofEnumMessage> =
  /*@__PURE__*/
  messageDesc(file_proto_oneofenum_oneof_enum, 0);

/**
 * @generated from enum proto.oneofenum.ExampleEnum
 */
export enum ExampleEnum {
  /**
   * @generated from enum value: EXAMPLE_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EXAMPLE_ENUM_FIRST = 1;
   */
  FIRST = 1,
}

/**
 * Describes the enum proto.oneofenum.ExampleEnum.
 */
export const ExampleEnumSchema: GenEnum<ExampleEnum> =
  /*@__PURE__*/
  enumDesc(file_proto_oneofenum_oneof_enum, 0);
