// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: proto/querystring/querystring.proto

/* eslint-disable */
import { type CallContext, type CallOptions } from "nice-grpc-common";
import { Any } from "../../google/protobuf/any";
import { Duration } from "../../google/protobuf/duration";
import { Empty } from "../../google/protobuf/empty";
import { FieldMask } from "../../google/protobuf/field_mask";
import { Timestamp } from "../../google/protobuf/timestamp";
import { ABitOfEverything } from "../examplepb/a_bit_of_everything";

export const protobufPackage = "proto.querystring";

export interface WellKnownTypesHolder {
  payloadCheck: string;
  any?: Any | undefined;
  empty?: Empty | undefined;
  struct?: { [key: string]: any } | undefined;
  value?: any | undefined;
  listValue?: Array<any> | undefined;
  timestamp?: Date | undefined;
  duration?: Duration | undefined;
  fieldMask?: string[] | undefined;
  boolValue?: boolean | undefined;
  int32Value?: number | undefined;
  uint32Value?: number | undefined;
  int64Value?: number | undefined;
  uint64Value?: number | undefined;
  stringValue?: string | undefined;
  bytesValue?: Uint8Array | undefined;
  doubleValue?: number | undefined;
  floatValue?: number | undefined;
}

function createBaseWellKnownTypesHolder(): WellKnownTypesHolder {
  return {
    payloadCheck: "",
    any: undefined,
    empty: undefined,
    struct: undefined,
    value: undefined,
    listValue: undefined,
    timestamp: undefined,
    duration: undefined,
    fieldMask: undefined,
    boolValue: undefined,
    int32Value: undefined,
    uint32Value: undefined,
    int64Value: undefined,
    uint64Value: undefined,
    stringValue: undefined,
    bytesValue: undefined,
    doubleValue: undefined,
    floatValue: undefined,
  };
}

export const WellKnownTypesHolder: MessageFns<WellKnownTypesHolder> = {
  fromJSON(object: any): WellKnownTypesHolder {
    return {
      payloadCheck: isSet(object.payloadCheck)
        ? globalThis.String(object.payloadCheck)
        : "",
      any: isSet(object.any) ? Any.fromJSON(object.any) : undefined,
      empty: isSet(object.empty) ? Empty.fromJSON(object.empty) : undefined,
      struct: isObject(object.struct) ? object.struct : undefined,
      value: isSet(object?.value) ? object.value : undefined,
      listValue: globalThis.Array.isArray(object.listValue)
        ? [...object.listValue]
        : undefined,
      timestamp: isSet(object.timestamp)
        ? fromJsonTimestamp(object.timestamp)
        : undefined,
      duration: isSet(object.duration)
        ? Duration.fromJSON(object.duration)
        : undefined,
      fieldMask: isSet(object.fieldMask)
        ? FieldMask.unwrap(FieldMask.fromJSON(object.fieldMask))
        : undefined,
      boolValue: isSet(object.boolValue)
        ? Boolean(object.boolValue)
        : undefined,
      int32Value: isSet(object.int32Value)
        ? Number(object.int32Value)
        : undefined,
      uint32Value: isSet(object.uint32Value)
        ? Number(object.uint32Value)
        : undefined,
      int64Value: isSet(object.int64Value)
        ? Number(object.int64Value)
        : undefined,
      uint64Value: isSet(object.uint64Value)
        ? Number(object.uint64Value)
        : undefined,
      stringValue: isSet(object.stringValue)
        ? String(object.stringValue)
        : undefined,
      bytesValue: isSet(object.bytesValue)
        ? new Uint8Array(object.bytesValue)
        : undefined,
      doubleValue: isSet(object.doubleValue)
        ? Number(object.doubleValue)
        : undefined,
      floatValue: isSet(object.floatValue)
        ? Number(object.floatValue)
        : undefined,
    };
  },

  toJSON(message: WellKnownTypesHolder): unknown {
    const obj: any = {};
    if (message.payloadCheck !== "") {
      obj.payloadCheck = message.payloadCheck;
    }
    if (message.any !== undefined) {
      obj.any = Any.toJSON(message.any);
    }
    if (message.empty !== undefined) {
      obj.empty = Empty.toJSON(message.empty);
    }
    if (message.struct !== undefined) {
      obj.struct = message.struct;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    if (message.listValue !== undefined) {
      obj.listValue = message.listValue;
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp.toISOString();
    }
    if (message.duration !== undefined) {
      obj.duration = Duration.toJSON(message.duration);
    }
    if (message.fieldMask !== undefined) {
      obj.fieldMask = FieldMask.toJSON(FieldMask.wrap(message.fieldMask));
    }
    if (message.boolValue !== undefined) {
      obj.boolValue = message.boolValue;
    }
    if (message.int32Value !== undefined) {
      obj.int32Value = message.int32Value;
    }
    if (message.uint32Value !== undefined) {
      obj.uint32Value = message.uint32Value;
    }
    if (message.int64Value !== undefined) {
      obj.int64Value = message.int64Value;
    }
    if (message.uint64Value !== undefined) {
      obj.uint64Value = message.uint64Value;
    }
    if (message.stringValue !== undefined) {
      obj.stringValue = message.stringValue;
    }
    if (message.bytesValue !== undefined) {
      obj.bytesValue = message.bytesValue;
    }
    if (message.doubleValue !== undefined) {
      obj.doubleValue = message.doubleValue;
    }
    if (message.floatValue !== undefined) {
      obj.floatValue = message.floatValue;
    }
    return obj;
  },

  create(base?: DeepPartial<WellKnownTypesHolder>): WellKnownTypesHolder {
    return WellKnownTypesHolder.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WellKnownTypesHolder>): WellKnownTypesHolder {
    const message = createBaseWellKnownTypesHolder();
    message.payloadCheck = object.payloadCheck ?? "";
    message.any =
      object.any !== undefined && object.any !== null
        ? Any.fromPartial(object.any)
        : undefined;
    message.empty =
      object.empty !== undefined && object.empty !== null
        ? Empty.fromPartial(object.empty)
        : undefined;
    message.struct = object.struct ?? undefined;
    message.value = object.value ?? undefined;
    message.listValue = object.listValue ?? undefined;
    message.timestamp = object.timestamp ?? undefined;
    message.duration =
      object.duration !== undefined && object.duration !== null
        ? Duration.fromPartial(object.duration)
        : undefined;
    message.fieldMask = object.fieldMask ?? undefined;
    message.boolValue = object.boolValue ?? undefined;
    message.int32Value = object.int32Value ?? undefined;
    message.uint32Value = object.uint32Value ?? undefined;
    message.int64Value = object.int64Value ?? undefined;
    message.uint64Value = object.uint64Value ?? undefined;
    message.stringValue = object.stringValue ?? undefined;
    message.bytesValue = object.bytesValue ?? undefined;
    message.doubleValue = object.doubleValue ?? undefined;
    message.floatValue = object.floatValue ?? undefined;
    return message;
  },
};

export type QueryStringServiceDefinition = typeof QueryStringServiceDefinition;
export const QueryStringServiceDefinition = {
  name: "QueryStringService",
  fullName: "proto.querystring.QueryStringService",
  methods: {
    getEnumQuerystring: {
      name: "GetEnumQuerystring",
      requestType: ABitOfEverything,
      requestStream: false,
      responseType: ABitOfEverything,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              33, 18, 31, 47, 118, 49, 47, 113, 117, 101, 114, 121, 115, 116,
              114, 105, 110, 103, 47, 101, 110, 117, 109, 113, 117, 101, 114,
              121, 115, 116, 114, 105, 110, 103,
            ]),
          ],
        },
      },
    },
    getStringQuerystring: {
      name: "GetStringQuerystring",
      requestType: ABitOfEverything,
      requestStream: false,
      responseType: ABitOfEverything,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              35, 18, 33, 47, 118, 49, 47, 113, 117, 101, 114, 121, 115, 116,
              114, 105, 110, 103, 47, 115, 116, 114, 105, 110, 103, 113, 117,
              101, 114, 121, 115, 116, 114, 105, 110, 103,
            ]),
          ],
        },
      },
    },
    getRepeatedEnumQuerystring: {
      name: "GetRepeatedEnumQuerystring",
      requestType: ABitOfEverything,
      requestStream: false,
      responseType: ABitOfEverything,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              41, 18, 39, 47, 118, 49, 47, 113, 117, 101, 114, 121, 115, 116,
              114, 105, 110, 103, 47, 114, 101, 112, 101, 97, 116, 101, 100,
              101, 110, 117, 109, 113, 117, 101, 114, 121, 115, 116, 114, 105,
              110, 103,
            ]),
          ],
        },
      },
    },
    getRepeatedStringQuerystring: {
      name: "GetRepeatedStringQuerystring",
      requestType: ABitOfEverything,
      requestStream: false,
      responseType: ABitOfEverything,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              43, 18, 41, 47, 118, 49, 47, 113, 117, 101, 114, 121, 115, 116,
              114, 105, 110, 103, 47, 114, 101, 112, 101, 97, 116, 101, 100,
              115, 116, 114, 105, 110, 103, 113, 117, 101, 114, 121, 115, 116,
              114, 105, 110, 103,
            ]),
          ],
        },
      },
    },
  },
} as const;

export interface QueryStringServiceImplementation<CallContextExt = {}> {
  getEnumQuerystring(
    request: ABitOfEverything,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ABitOfEverything>>;
  getStringQuerystring(
    request: ABitOfEverything,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ABitOfEverything>>;
  getRepeatedEnumQuerystring(
    request: ABitOfEverything,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ABitOfEverything>>;
  getRepeatedStringQuerystring(
    request: ABitOfEverything,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ABitOfEverything>>;
}

export interface QueryStringServiceClient<CallOptionsExt = {}> {
  getEnumQuerystring(
    request: DeepPartial<ABitOfEverything>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ABitOfEverything>;
  getStringQuerystring(
    request: DeepPartial<ABitOfEverything>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ABitOfEverything>;
  getRepeatedEnumQuerystring(
    request: DeepPartial<ABitOfEverything>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ABitOfEverything>;
  getRepeatedStringQuerystring(
    request: DeepPartial<ABitOfEverything>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ABitOfEverything>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
