// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file proto/sub2/message.proto (package proto.sub2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sub2/message.proto.
 */
export const file_proto_sub2_message: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Chhwcm90by9zdWIyL21lc3NhZ2UucHJvdG8SCnByb3RvLnN1YjIiGQoJSWRNZXNzYWdlEgwKBHV1aWQYASABKAlCrwEKDmNvbS5wcm90by5zdWIyQgxNZXNzYWdlUHJvdG9QAVpGZ2l0aHViLmNvbS9ncnBjLWVjb3N5c3RlbS9ncnBjLWdhdGV3YXkvdjIvZXhhbXBsZXMvaW50ZXJuYWwvcHJvdG8vc3ViMqICA1BTWKoCClByb3RvLlN1YjLKAgpQcm90b1xTdWIy4gIWUHJvdG9cU3ViMlxHUEJNZXRhZGF0YeoCC1Byb3RvOjpTdWIyYgZwcm90bzM",
  );

/**
 * @generated from message proto.sub2.IdMessage
 */
export type IdMessage = Message<"proto.sub2.IdMessage"> & {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;
};

/**
 * Describes the message proto.sub2.IdMessage.
 * Use `create(IdMessageSchema)` to create a new message.
 */
export const IdMessageSchema: GenMessage<IdMessage> =
  /*@__PURE__*/
  messageDesc(file_proto_sub2_message, 0);
