//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.6
//- protoc 5.28.2
//source: proto/feed/feed.proto

package feed

import (
	user "github.com/RyoJerryYu/protoc-gen-plugins/tests/protoc-gen-go-fieldmask/e2e/proto/user"
)

// IFeedFieldPath is the interface for the field path of Feed
type IFeedFieldPath interface {
	String() string
	Id() string
	Title() string
	Author() user.IUserFieldPath
	CreatedAt() string
	NestedFromOther() user.IIcon_NestedFieldPath
}

// feedFieldPath is the implementation for the field path of Feed
type feedFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewFeedFieldPath creates a new feedFieldPath
func NewFeedFieldPath(fieldPath string) IFeedFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return feedFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x feedFieldPath) String() string { return x.fieldPath }

func (x feedFieldPath) Id() string    { return x.prefix + "id" }
func (x feedFieldPath) Title() string { return x.prefix + "title" }
func (x feedFieldPath) Author() user.IUserFieldPath {
	return user.NewUserFieldPath(x.prefix + "author")
}
func (x feedFieldPath) CreatedAt() string { return x.prefix + "created_at" }
func (x feedFieldPath) NestedFromOther() user.IIcon_NestedFieldPath {
	return user.NewIcon_NestedFieldPath(x.prefix + "nested_from_other")
}

// FieldPath returns the field path for Feed
func (x *Feed) FieldPath() IFeedFieldPath {
	return NewFeedFieldPath("")
}
